[options]

admin_passwd = hb_admin_2026

db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = hbi1974

addons_path = /home/hbinstitute/Documents/H.B.INSTITUTE - ERP/odoo/addons,/home/hbinstitute/Documents/H.B.INSTITUTE - ERP/custom_addons

http_port = 8069

logfile = /home/hbinstitute/Documents/H.B.INSTITUTE - ERP/logs/odoo.log


